apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ac-portal-prod

namespace: ac-portal-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- route-patch.yaml
- configmap-patch.yaml

commonLabels:
  environment: production

images:
- name: ac-portal
  newTag: prod