apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ac-portal-base

resources:
  - imagestream.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: ac-portal

images:
  - name: ac-portal
    newTag: latest
