apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-portal
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ac-portal
          env:
            - name: MINIO_PUBLIC_BASE
              value: https://minio-staging.appcarrier.cloud
